# SAM & docker-compose
# https://github.com/awslabs/aws-sam-local/issues/55

version: '2'
services:
  website: 
    build: 
      context: ./react-redux-starter
      dockerfile: .docker/react.node.awscli.dockerfile
    env_file:
      - ./.secrets.env
    volumes: 
      - ./react-redux-starter:/var/www
    ports:
      - "3000:3000"
    command: npm start
  lambda: 
    build: 
      context: ./lambda-rest-starter
      dockerfile: .docker/awssam.node9.awscli.dockerfile
    environment:
      - SAM_DOCKER_VOLUME_BASEDIR=$PWD/lambda-rest-starter
    env_file:
      - ./.secrets.env
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./lambda-rest-starter:/home/neo/app
    ports:
      - "3001:3000"
    command: npm start


# ----------------------------------------------------------------------------------
# default 
# ----------------------------------------------------------------------------------
# docker-compose build
# docker-compose up


# ----------------------------------------------------------------------------------
# website 
# ----------------------------------------------------------------------------------
# docker-compose build
# docker-compose run --rm --service-ports website npm run build
# docker-compose run website aws --version


# ----------------------------------------------------------------------------------
# lambda 
# ----------------------------------------------------------------------------------
# docker-compose build
# docker-compose run --rm --service-ports lambda npm run build
# 
# https://github.com/awslabs/aws-sam-local/issues/208
# docker-compose run --rm --user root --service-ports lambda /home/neo/.npm-global/bin/sam local start-api -t /home/neo/app/sam.yml --host 0.0.0.0




# docker run --rm --env-file .secrets.env -p 3000:3000 -v $(PWD):/home/neo/app node9-awscli npm run create-stack